package crossMapper_V0_1;

import java.awt.event.ActionEvent;
//import java.awt.event.ItemEvent;

/**
 *
 * @author lmosulli
 */
public class SerialSettingsMenu extends javax.swing.JFrame {

    /** Creates new form SerialSettingsMenu */
    public SerialSettingsMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baudRate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialEnabled = new javax.swing.JCheckBox();
        portName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        delimiter = new javax.swing.JTextField();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        baudRate.setColumns(6);
        baudRate.setText("N/A");
        baudRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baudRateFldActionPerformed(evt);
            }
        });

        jLabel1.setText("Baud Rate");
        jLabel2.setText("Com Port Name");

        serialEnabled.setText("Enable Serial Communications");
        serialEnabled.setSelected(false);
        serialEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialEnabledFldActionPerformed(evt);
            }
        });
        portName.setColumns(6);
        portName.setText("N/A");
        portName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	portNameFldActionPerformed(evt);
            }
        });
        
        jLabel3.setText("Delimiter");
        delimiter.setSize(3, 12);
        delimiter.setText(",");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(serialEnabled)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delimiter, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(portName)
                                .addComponent(baudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(serialEnabled)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(portName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(baudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delimiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void serialEnabledFldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
    	//System.out.println("The event is: "+ evt);
    	//System.out.println("The entered port number is: "+ Integer.parseInt(evt.getActionCommand()));
    if(serialEnabled.isSelected()){	
    	CrossMapper_V0_1_Start.myMapperV3.serialEnabled =true;
    	CrossMapper_V0_1_Start.myMapperV3.serialInitialise();
    	System.out.println("Baud rate is: "+ CrossMapper_V0_1_Start.myMapperV3.baudRate);
        baudRate.setText(Integer.toString(CrossMapper_V0_1_Start.myMapperV3.baudRate));
        portName.setText(CrossMapper_V0_1_Start.myMapperV3.comPort);
    }
    else{
    	if (CrossMapper_V0_1_Start.myMapperV3.serialEnabled =true){;
    	CrossMapper_V0_1_Start.myMapperV3.serialStop();
    	CrossMapper_V0_1_Start.myMapperV3.serialEnabled =false;
    	baudRate.setText(Integer.toString(CrossMapper_V0_1_Start.myMapperV3.baudRate));
        portName.setText(CrossMapper_V0_1_Start.myMapperV3.comPort);
    	}
    }
    } 

private void baudRateFldActionPerformed(ActionEvent evt) {
	// TODO Auto-generated method stub
	System.out.println("The entered Baud Rate is: "+ Integer.parseInt(evt.getActionCommand()));
	if(serialEnabled.isSelected()){
		CrossMapper_V0_1_Start.myMapperV3.serialStop();
		CrossMapper_V0_1_Start.myMapperV3.serialBaudChanged(Integer.parseInt(evt.getActionCommand()));
		CrossMapper_V0_1_Start.myMapperV3.serialInitialise();
		
}
	else{
		CrossMapper_V0_1_Start.myMapperV3.serialBaudChanged(Integer.parseInt(evt.getActionCommand()));
	
	}
}

private void portNameFldActionPerformed(ActionEvent evt) {
	// TODO Auto-generated method stub
	System.out.println("The entered Port Name is: "+ (evt.getActionCommand()));
        CrossMapper_V0_1_Start.myMapperV3.comPort = evt.getActionCommand(); //update the COM Port
	System.out.println("The system will use Port: "+ CrossMapper_V0_1_Start.myMapperV3.comPort);
	/*if(serialEnabled.isSelected()){
		MapperV3Start.myMapperV3.serialStop();
		MapperV3Start.myMapperV3.serialPortChanged(evt.getActionCommand());
		MapperV3Start.myMapperV3.serialInitialise();
		
}
	else{
		MapperV3Start.myMapperV3.serialPortChanged(evt.getActionCommand());
	
	}
	*/
}

static public void serialNotAvailable(){
	serialEnabled.setSelected(false);
	baudRate.setText(Integer.toString(CrossMapper_V0_1_Start.myMapperV3.baudRate));
    portName.setText(CrossMapper_V0_1_Start.myMapperV3.comPort);
	
}
   

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static private javax.swing.JTextField baudRate;
    private javax.swing.JTextField delimiter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    static private javax.swing.JTextField portName;
    static private javax.swing.JCheckBox serialEnabled;
    // End of variables declaration//GEN-END:variables

}
